# Kernso MCP Server
# Multi-stage build, runs as non-root user
# Works for both: docker run -i (stdio) and HTTP (Cloud Run)

FROM python:3.12-slim AS base

RUN groupadd -r kernso && useradd -r -g kernso -m kernso

WORKDIR /app

# Install system deps
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

# Copy pip config (generated by Cloud Build with AR credentials)
COPY pip.conf /etc/pip.conf

# Install Python deps (pip.conf provides AR auth)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY src/ src/

ENV PYTHONPATH=/app/src

# Switch to non-root
USER kernso

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
    CMD curl -f http://localhost:8080/health || exit 1

# Default: HTTP mode for Cloud Run
CMD ["python", "-m", "kernso_mcp.server", "--port", "8080"]
